// MODAL
export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';

export const MODAL_REG_OPEN = 'MODAL_REG_OPEN';
export const MODAL_REG_CLOSE = 'MODAL_REG_CLOSE';

export const MODAL_DATASET_OPEN = 'MODAL_DATASET_OPEN';
export const MODAL_DATASET_CLOSE = 'MODAL_DATASET_CLOSE';

// MESSAGE
export const MESSAGE_SHOW = 'MESSAGE_SHOW';

// ACCOUNT
export const ACCOUNT_AUTH_REQUEST = 'ACCOUNT_AUTH_REQUEST';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REG_REQUEST = 'ACCOUNT_REG_REQUEST';
export const ACCOUNT_REG_SUCCESS = 'ACCOUNT_REG_SUCCESS';
export const ACCOUNT_REG_FAIL = 'ACCOUNT_REG_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

// DATA LOADER 
export const LOADER_GET_REQUEST = 'LOADER_GET_REQUEST';
export const LOADER_GET_SUCCESS = 'LOADER_GET_SUCCESS';
export const LOADER_GET_FAIL = 'LOADER_GET_FAIL';

// DATASET LIST
export const DATASET_SELECT = 'DATASET_SELECT';
export const DATASET_DELETE = 'DATASET_DELETE';
export const DATASET_SET_SORT = 'DATASET_SET_SORT';