// MODAL
export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';

export const MODAL_REG_OPEN = 'MODAL_REG_OPEN';
export const MODAL_REG_CLOSE = 'MODAL_REG_CLOSE';

// MESSAGE
export const MESSAGE_SHOW = 'MESSAGE_SHOW';

// ACCOUNT
export const ACCOUNT_AUTH_REQUEST = 'ACCOUNT_AUTH_REQUEST';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAIL';

export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REG_REQUEST = 'ACCOUNT_REG_REQUEST';
export const ACCOUNT_REG_SUCCESS = 'ACCOUNT_REG_SUCCESS';
export const ACCOUNT_REG_FAIL = 'ACCOUNT_REG_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';
