export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';

export const MODAL_REGISTER_OPEN = 'MODAL_REGISTER_OPEN';
export const MODAL_REGISTER_CLOSE = 'MODAL_REGISTER_CLOSE';

export const ACCOUNT_AUTH_LOADING = 'ACCOUNT_AUTH_LOADING';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAUL';

export const ACCOUNT_LOGIN_LOADING = 'ACCOUNT_LOGIN_LOADING';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REGISTER = 'ACCOUNT_REGISTER';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';