export const MODAL_LOGIN_OPEN = 'MODAL_LOGIN_OPEN';
export const MODAL_LOGIN_CLOSE = 'MODAL_LOGIN_CLOSE';

export const MODAL_REGISTER_OPEN = 'MODAL_REGISTER_OPEN';
export const MODAL_REGISTER_CLOSE = 'MODAL_REGISTER_CLOSE';

export const ACCOUNT_AUTH_LOADING = 'ACCOUNT_AUTH_LOADING';
export const ACCOUNT_AUTH_SUCCESS = 'ACCOUNT_AUTH_SUCCESS';
export const ACCOUNT_AUTH_FAIL = 'ACCOUNT_AUTH_FAUL';

export const ACCOUNT_LOGIN_LOADING = 'ACCOUNT_LOGIN_LOADING';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL';

export const ACCOUNT_REGISTER_LOADING = 'ACCOUNT_REGISTER_LOADING';
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS';
export const ACCOUNT_REGISTER_FAIL = 'ACCOUNT_REGISTER_FAIL';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';

export const ALGO_LIST_LOADING = 'ALGO_LIST_LOADING';
export const ALGO_LIST_SUCCESS = 'ALGO_LIST_SUCCESS';
export const ALGO_LIST_FAIL = 'ALGO_LIST_FAIL';

export const ALGO_EXECUTE_LOADING = 'ALGO_EXECUTE_LOADING';
export const ALGO_EXECUTE_SUCCESS = 'ALGO_EXECUTE_SUCCESS';
export const ALGO_EXECUTE_FAIL = 'ALGO_EXECUTE_FAIL';

export const DATA_GET_LOADING = 'DATA_LOADING';
export const DATA_GET_SUCCESS = 'DATA_SUCCESS';
export const DATA_GET_FAIL = 'DATA_FAIL';